CREATE DATABASE AdsServiceDB;
GO

USE AdsServiceDB;
GO

CREATE TABLE Cities (
    Id INT PRIMARY KEY IdENTITY(1,1),
    Name NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Categories (
    Id INT PRIMARY KEY IdENTITY(1,1),
    Name NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Ad_Types (
    Id INT PRIMARY KEY IdENTITY(1,1),
    Name NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Ad_Statuses (
    Id INT PRIMARY KEY IdENTITY(1,1),
    Name NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Users (
    Id INT PRIMARY KEY IdENTITY(1,1),
    User_login NVARCHAR(50) NOT NULL UNIQUE,
    User_password NVARCHAR(255) NOT NULL
);

CREATE TABLE Advertisements (
    Id INT PRIMARY KEY IdENTITY(1,1),
    Ad_title NVARCHAR(200) NOT NULL,
    Ad_description NVARCHAR(MAX),
    Ad_post_date DATETIME NOT NULL DEFAULT GETDATE(),
    
	Ad_photo VARBINARY(MAX) NULL;
    Price DECIMAL(18,2) NOT NULL CHECK (Price >= 0),
    
    User_Id INT NOT NULL REFERENCES Users(Id) ON DELETE CASCADE ON UPDATE CASCADE,
    City_Id INT NOT NULL REFERENCES Cities(Id),
    Category_Id INT NOT NULL REFERENCES Categories(Id),
    Ad_type_Id INT NOT NULL REFERENCES Ad_Types(Id),
    Ad_status_Id INT NOT NULL REFERENCES Ad_Statuses(Id)
);
GO
