//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goman_WPF_PROJ_UP02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisements
    {
        public int Id { get; set; }
        public string Ad_title { get; set; }
        public string Ad_description { get; set; }
        public System.DateTime Ad_post_date { get; set; }
        public decimal Price { get; set; }
        public int User_Id { get; set; }
        public int City_Id { get; set; }
        public int Category_Id { get; set; }
        public int Ad_type_Id { get; set; }
        public int Ad_status_Id { get; set; }
        public byte[] Ad_photo { get; set; }
    
        public virtual Ad_Statuses Ad_Statuses { get; set; }
        public virtual Ad_Types Ad_Types { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Users Users { get; set; }
    }
}
