//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goman_WPF_PROJ_UP02
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdsServiceDBEntities : DbContext
    {
        private static AdsServiceDBEntities _context;
        public static AdsServiceDBEntities GetContext()
        {
            if (_context == null)
            {
                _context = new AdsServiceDBEntities();
            }
            return _context;
        }
        public AdsServiceDBEntities()
            : base("name=AdsServiceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad_Statuses> Ad_Statuses { get; set; }
        public virtual DbSet<Ad_Types> Ad_Types { get; set; }
        public virtual DbSet<Advertisements> Advertisements { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
